version: "3"

networks:
  my_net:

volumes:
  idealoom_static:
  pgdata:
  redisdata:

services:
  redis:
    image: redis:3.0-alpine
    volumes:
      - redisdata:/data
    networks:
      - my_net

  memcached:
    image: memcached:1.4-alpine
    networks:
      - my_net

  database:
    image: postgres:9.5.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_net

  web:
    image: nginx:1.12-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx_config_docker:/opt/default_config
      - idealoom_static:/opt/idealoom_static
    environment:
      IDEALOOM_HOST: idealoom1
      PUBLIC_HOSTNAME: idealoom1.local
      http_upgrade: '$http_upgrade'
    depends_on:
      - idealoom1
    command: /bin/sh -c "sed -e 's/IDEALOOM_HOST/idealoom1/; s/PUBLIC_HOSTNAME/idealoom1.local/;' < /opt/default_config/default > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - my_net

  idealoom1:
    image: idealoom:latest
    ports:
      - "8090:8090"
    volumes:
      - ../var/docker/stack1:/var/docker_data
      - idealoom_static:/opt/idealoom_static
    environment:
      DOCKER_RC: /var/docker_data/idealoom1.rc
      BUILDING_DOCKER: "false"
    depends_on:
      - redis
      - memcached
      - database
    command: sh -c 'cd /opt/idealoom; /etc/init.d/ssh start ; chown idealoom_user /opt/idealoom_static; . venv/bin/activate ; env BUILDING_DOCKER=false fab -c /var/docker_data/idealoom1.rc docker_startup ; tail -f /dev/null'
    networks:
      - my_net
